version: '3'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    ports:
      - "4444:4444"
    volumes:
      - "./:/opt/selenium"

  chrome:
    image: selenium/node-chrome-debug:4.14.0-20230925
    depends_on:
      - selenoid
    environment:
      HUB_HOST: selenoid
      SE_NODE_MAX_SESSIONS: 1
